"""Verified recent Information Fusion metadata; no external metadata invention."""
import json
from pathlib import Path

BASE = Path(__file__).parent
rows = [
    dict(key='Han2026QPBayes', title='Adaptive probabilistic information fusion under concept drift: a generalized bayesian framework', authors=['Lincheng Han','Xiuyu Zhang','Jianguo Wang'], bib_authors='Han, Lincheng and Zhang, Xiuyu and Wang, Jianguo', year=2026, volume='129', article_number='104010', month='May', doi='10.1016/j.inffus.2025.104010', pii='S1566253525010723',
         abstract_claims='Uses generalized Bayesian inference with CRPS for nonstationary probabilistic forecast combination. QP-Bayes relates Bayesian MAP filtering to quadratic programming; UKF-Bayes treats simplex constraints through latent variables. Weight uncertainty and online adaptation are assessed on synthetic drift and NREL wind forecasts.',
         fit_to_method='Closest recent neighbor. Bayesian-plus-convex weight adaptation alone cannot establish our novelty. Distinguish the action-projected joint forecast-error posterior, preservation of actually co-observed error blocks, and cost-inclusive calibrated fixed-horizon deployment admissions. Do not imply this paper evaluates our lease or delayed outcome contract.'),
    dict(key='Shao2024DDEF', title='Dual-level Deep Evidential Fusion: Integrating multimodal information for enhanced reliable decision-making in deep learning', authors=['Zhimin Shao','Weibei Dou','Yu Pan'], bib_authors='Shao, Zhimin and Dou, Weibei and Pan, Yu', year=2024, volume='103', article_number='102113', month='March', doi='10.1016/j.inffus.2023.102113', pii='S1566253523004293',
         abstract_claims='Connects neural outputs to Dirichlet parameters and basic belief assignments. Dempster-Shafer theory combines evidence at assignment and modality levels. Evaluations include digit classification and medical prognosis following brain-computer interface treatment.',
         fit_to_method='Supports the established importance of uncertainty and modality reliability in fusion. Its evidential class prediction differs from a Bayesian posterior over action-error block corrections and an uncertainty-calibrated paid admission decision.'),
    dict(key='Huang2025Evidential', title='Deep evidential fusion with uncertainty quantification and reliability learning for multimodal medical image segmentation', authors=['Ling Huang','Su Ruan','Pierre Decazes','Thierry Denœux'], bib_authors=r'Huang, Ling and Ruan, Su and Decazes, Pierre and Den{\oe}ux, Thierry', year=2025, volume='113', article_number='102648', month='January', doi='10.1016/j.inffus.2024.102648', pii='S1566253524004263',
         abstract_claims='Maps modality features to voxel-level Dempster-Shafer mass functions, learns source reliability relative to each class through contextual discounting, and combines discounted evidence using Dempster\u2019s rule. PET-CT and multi-MRI segmentation experiments assess uncertainty and accuracy.',
         fit_to_method='Context-dependent reliability is prior art. Our causal contextual importance must use current observable features and past audit residuals; it does not condition execution on unknown future truth. Our target is the joint error of an update decision rather than evidential image segmentation.',
         supplementary_primary_urls=['https://www.hds.utc.fr/en/research/research-teams/cid-knowledge-uncertainty-data/'],
         verification_note='Publisher verifies title, full author order, issue year, volume and article number; author institutional publication list verifies DOI. The earlier local 2025.102648 DOI is wrong: DOI year is 2024, issue year is 2025.'),
    dict(key='Folgado2023Explainability', title='Explainability meets uncertainty quantification: Insights from feature-based model fusion on multimodal time series', authors=['Duarte Folgado','Marília Barandas','Lorenzo Famiglini','Ricardo Santos','Federico Cabitza','Hugo Gamboa'], bib_authors=r'Folgado, Duarte and Barandas, Mar{\'i}lia and Famiglini, Lorenzo and Santos, Ricardo and Cabitza, Federico and Gamboa, Hugo', year=2023, volume='100', article_number='101955', month='December', doi='10.1016/j.inffus.2023.101955', pii='S1566253523002713',
         abstract_claims='Studies uncertainty-guided feature-based late fusion of multimodal time series to reduce explanation complexity while preserving predictive performance. Physiological multimodal datasets motivate links among uncertainty, explanation complexity and missing information.',
         fit_to_method='Demonstrates an established operational role for predictive uncertainty in selecting modality contributions. Our additional question is whether posterior uncertainty changes costly update admissions and measured net utility under delayed feedback.',
         supplementary_primary_urls=['https://novaresearch.unl.pt/files/84028602/Explainability_meets_uncertainty_quantification.pdf']),
    dict(key='Liu2024MTMSA', title='Modality translation-based multimodal sentiment analysis under uncertain missing modalities', authors=['Zhizhong Liu','Bin Zhou','Dianhui Chu','Yuhang Sun','Lingqiang Meng'], bib_authors='Liu, Zhizhong and Zhou, Bin and Chu, Dianhui and Sun, Yuhang and Meng, Lingqiang', year=2024, volume='101', article_number='101973', month='January', doi='10.1016/j.inffus.2023.101973', pii='S1566253523002890',
         abstract_claims='Translates visual and audio inputs to text, constructs missing joint features, and uses a pretrained modality-translation network to supervise representations approximating complete modalities. Transformer modules learn intermodal dependencies; experiments use CMU-MOSI and IEMOCAP.',
         fit_to_method='Representative missing-modality reconstruction. Our joint error memory does not claim reconstructed views were co-observed; it retains identifiable observed sub-blocks and uses only available forecasts at execution.'),
    dict(key='Chai2023Heterogeneous', title='Heterogeneous multi-sensor fusion for PHD filter in decentralized sensor networks', authors=['Lei Chai','Wei Yi','Reza Hoseinnezhad','Lingjiang Kong'], bib_authors='Chai, Lei and Yi, Wei and Hoseinnezhad, Reza and Kong, Lingjiang', year=2023, volume='100', article_number='101956', month='December', doi='10.1016/j.inffus.2023.101956', pii='S1566253523002725',
         abstract_claims='Develops heterogeneous fusion of multi-object Poisson densities with space-varying information confidence. Density-based weights measure relative local confidence without requiring sensor or environmental knowledge; consensus and flooding extend the method to decentralized networks.',
         fit_to_method='Reliability varying by state and sensor is established. Our weights jointly penalize action-important cross-source error covariance and posterior correction uncertainty, for classification deployment decisions rather than probability hypothesis density tracking.'),
    dict(key='Zhang2024CommonInfo', title='Discovering common information in multi-view data', authors=['Qi Zhang','Mingfei Lu','Shujian Yu','Jingmin Xin','Badong Chen'], bib_authors='Zhang, Qi and Lu, Mingfei and Yu, Shujian and Xin, Jingmin and Chen, Badong', year=2024, volume='108', article_number='102400', month='August', doi='10.1016/j.inffus.2024.102400', pii='S1566253524001787',
         abstract_claims='Defines common information inspired by Gács-Körner information and learns common and unique multi-view representations. Minimizing total correlation encourages their independence; matrix-based Rényi entropy estimates information quantities. Theory and real benchmark experiments support the construction.',
         fit_to_method='Useful for explaining complementarity and redundancy. Its information-theoretic common/unique decomposition is not equivalent to an action-error covariance; our contribution is decision-specific dependence and observed-block posterior estimation.',
         supplementary_primary_urls=['https://research.vu.nl/en/publications/discovering-common-information-in-multi-view-data/','https://research.vu.nl/ws/portalfiles/portal/362837517/Discovering_common_information_in_multi-view_data.pdf'],
         verification_note='Publisher metadata and author institutional version-of-record PDF jointly verify all fields and DOI.'),
    dict(key='Hu2024DelayedFusion', title='Distributed fusion filtering for multi-sensor nonlinear networked systems with multiple fading measurements via stochastic communication protocol', authors=['Jun Hu','Zhibin Hu','Raquel Caballero-Águila','Xiaojian Yi'], bib_authors=r'Hu, Jun and Hu, Zhibin and Caballero-{\'A}guila, Raquel and Yi, Xiaojian', year=2024, volume='112', article_number='102543', month='December', doi='10.1016/j.inffus.2024.102543', pii='S156625352400321X',
         abstract_claims='Develops inverse-covariance-intersection fusion for nonlinear delayed multisensor systems with fading measurements and stochastic communication. Local filtering error covariance upper bounds are minimized through filter gains, and sufficient conditions yield uniform boundedness; evidence comprises two simulation examples.',
         fit_to_method='Delayed measurements, incomplete communications and conservative dependent-source fusion are established problems. Our setting is delayed labels for immutable forecasts and exact realized gain of bounded paid canaries, not state-estimation covariance guarantees.',
         supplementary_primary_urls=['https://investigacion.ujaen.es/documentos/66939b9b19f8ae74e233b6f8','https://ruja.ujaen.es/bitstream/10953/3163/1/2024_INFFUS_preprrint.pdf'],
         verification_note='Publisher verifies title, authors, issue year, volume, article number and abstract; author institutional repository verifies DOI.'),
    dict(key='Sun2026DSHBI', title='DS-HBI: Dual-stream fusion forecasting model with historical backfilling imputation', authors=['Dezhi Sun','Jiwei Qin','Weilin Tang','Xizhong Qin','Fei Shi','Minrui Wang','Zhenliang Liao'], bib_authors='Sun, Dezhi and Qin, Jiwei and Tang, Weilin and Qin, Xizhong and Shi, Fei and Wang, Minrui and Liao, Zhenliang', year=2026, volume='127', part='A', article_number='103761', month='March', doi='10.1016/j.inffus.2025.103761', pii='S1566253525008231',
         abstract_claims='Fuses a raw incomplete-sequence branch with a branch reconstructed through dynamic time warping and probabilistic historical imputation. Gated attention balances the branches. Forecasting of atmospheric carbon concentrations is evaluated on multisite TCCON data, including high missingness.',
         fit_to_method='History, missingness and adaptive fusion are active topics. Our archive preserves when forecasts genuinely co-existed, rather than backfilling absent predictions; our measured endpoint is update utility after explicit admission, restoration and service-drop costs.'),
    dict(key='Li2024MVCIL', title='Multi-view class incremental learning', authors=['Depeng Li','Tianqi Wang','Junwei Chen','Kenji Kawaguchi','Cheng Lian','Zhigang Zeng'], bib_authors='Li, Depeng and Wang, Tianqi and Chen, Junwei and Kawaguchi, Kenji and Lian, Cheng and Zeng, Zhigang', year=2024, volume='102', article_number='102021', month='February', doi='10.1016/j.inffus.2023.102021', pii='S1566253523003378',
         abstract_claims='Learns new classes from a continual stream of views without retaining prior views. Randomized view representations, orthogonality fusion and selective weight consolidation combine evolving information while limiting forgetting; synthetic and real datasets assess the method.',
         fit_to_method='Incremental multi-view learning supplies context for evolving inputs. Our experiments fix the class metadata and train common candidate/reference models causally; they do not establish class-incremental learning or protection against catastrophic forgetting.'),
    dict(key='Wang2024SEMI', title='Incomplete multi-view clustering via structure exploration and missing-view inference', authors=['Ziyu Wang','Lusi Li','Xin Ning','Wenkai Tan','Yongxin Liu','Houbing Song'], bib_authors='Wang, Ziyu and Li, Lusi and Ning, Xin and Tan, Wenkai and Liu, Yongxin and Song, Houbing', year=2024, volume='103', article_number='102123', month='March', doi='10.1016/j.inffus.2023.102123', pii='S1566253523004396',
         abstract_claims='Jointly explores global, local, consistent and inconsistent structures through self-expression, graph and partition learning. A unified coefficient matrix guides missing-view inference, and alternating optimization links reconstruction and clustering.',
         fit_to_method='Shows why missing-view reconstruction can inject noise or bias when inconsistent structure is ignored. Our observed-block protocol avoids inventing joint errors for unavailable forecasts; it does not perform clustering or reconstruct missing raw modalities.'),
    dict(key='Ge2025Credibility', title='Credibility-based multi-sensor fusion for non-Gaussian conversion error mitigation', authors=['Quanbo Ge','Kai Lin','Zhongyuan Zhao'], bib_authors='Ge, Quanbo and Lin, Kai and Zhao, Zhongyuan', year=2025, volume='115', article_number='102704', month='March', doi='10.1016/j.inffus.2024.102704', pii='S1566253524004822',
         abstract_claims='Addresses non-Gaussian coordinate-conversion errors through credibility-based distributed sensor fusion, optimized error-distribution estimation, trustworthiness-adaptive particle swarm optimization and maximum-correntropy consensus for inconsistent local estimates.',
         fit_to_method='Motivates caution about treating covariance as universally sufficient. Our bounded action-error moments support a particular calibrated decision rule; they do not establish robustness to arbitrary non-Gaussian sensor transformation errors.'),
]

for r in rows:
    r['journal'] = 'Information Fusion'
    r['primary_url'] = 'https://www.sciencedirect.com/science/article/pii/' + r['pii']
    r['doi_url'] = 'https://doi.org/' + r['doi']
    r['verified_on'] = '2026-10-02'
    r.setdefault('verification_note', 'All bibliographic fields verified from primary Elsevier publisher search-index content; DOI publication year may precede the issue year. Crossref API was unavailable in this subagent environment, so no Crossref verification is claimed.')

out = {
    'purpose': 'Recent Information Fusion primary-source bibliography verification for Introduction and Related Work.',
    'selection_rule': 'Information Fusion journal, assigned issue year 2023--2026; currently available by 2026-10-02; methodological relevance to uncertainty, dependence, dynamic fusion or incomplete sources. Do not count DOI year as issue year.',
    'count': len(rows),
    'primary_source_limitations': 'Some direct publisher page opens fail; cached primary publisher search text and author institutional repositories were used. No secondary-only fields are represented as verified.',
    'critical_novelty_warning': 'Han2026QPBayes already connects generalized Bayesian filtering, convex quadratic weight optimization, drift adaptation and weight uncertainty. Distinguish our action-specific joint error posterior, factual missing-block preservation, and calibrated costly finite-horizon admission contract. Bayesian plus convex optimization alone is not a novel contribution.',
    'entries': rows,
}
(BASE / 'if_recent_refs.json').write_text(json.dumps(out, ensure_ascii=False, indent=2)+'\n')

bib = []
for r in rows:
    fields = [
        ('author',r['bib_authors']),('title','{'+r['title']+'}'),('journal','Information Fusion'),
        ('year',str(r['year'])),('volume',r['volume']),('pages',r['article_number']),('doi',r['doi']),('url',r['primary_url'])]
    if 'part' in r: fields.append(('note','Part '+r['part']))
    bib.append('@article{'+r['key']+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields)+'\n}\n')
(BASE / 'if_recent_refs.bib').write_text('\n'.join(bib))
print(json.dumps({'count':len(rows),'years':{y:sum(r['year']==y for r in rows) for y in range(2023,2027)},'keys':[r['key'] for r in rows]},indent=2))
